import imageOne from '../assets/images/Kvanndalfoss_1.jpg'
import imageTwo from '../assets/images/Amdal_1.jpg'

export const Image_Values = [
    { src: `${imageOne}`, classes: "img img-lg-ctr", altText: "Camille and Alan at Kvanndalfossen.", id: "1", blogEntry: "We hiked here and it was cool. I think we will probably hike there again, but maybe not. Who knows? Better follow our blog to find out." },
    { src: `${imageTwo}`, classes: "img img-lg-ctr", altText: "Lone hytte near Amdal.", id: "2", blogEntry: "There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever." },
    { src: `${imageOne}`, classes: "img img-lg-ctr", altText: "Camille and Alan at Kvanndalfossen.", id: "3", blogEntry: "We hiked here and it was cool. I think we will probably hike there again, but maybe not. Who knows? Better follow our blog to find out." },
    { src: `${imageTwo}`, classes: "img img-lg-ctr", altText: "Lone hytte near Amdal.", id: "4", blogEntry: "There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever." },
    { src: `${imageOne}`, classes: "img img-lg-ctr", altText: "Camille and Alan at Kvanndalfossen.", id: "5", blogEntry: "We hiked here and it was cool. I think we will probably hike there again, but maybe not. Who knows? Better follow our blog to find out." },
    { src: `${imageTwo}`, classes: "img img-lg-ctr", altText: "Lone hytte near Amdal.", id: "6", blogEntry: "There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever." },
    { src: `${imageOne}`, classes: "img img-lg-ctr", altText: "Camille and Alan at Kvanndalfossen.", id: "7", blogEntry: "We hiked here and it was cool. I think we will probably hike there again, but maybe not. Who knows? Better follow our blog to find out." },
    { src: `${imageTwo}`, classes: "img img-lg-ctr", altText: "Lone hytte near Amdal.", id: "8", blogEntry: "There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever. There is some stuff here!!!! And we'll go on forever." },
  ];